"""Write a TELEMAC .liq liquid boundary time series file."""
from __future__ import annotations
import numpy as np
from telemac_tools.model import BoundaryCondition, BCType


def _liq_column_name(bc: BoundaryCondition, bc_index: int) -> tuple[str, str]:
    """Return (column_header, unit) for a boundary condition.

    TELEMAC convention:
      Q(n)  — prescribed flow at boundary n  (m3/s)
      SL(n) — prescribed stage at boundary n (m)
    """
    idx = bc_index + 1  # 1-based in TELEMAC
    if bc.bc_type == BCType.FLOW:
        return f"Q({idx})", "m3/s"
    elif bc.bc_type == BCType.STAGE:
        return f"SL({idx})", "m"
    else:
        return f"Q({idx})", "m3/s"


def write_liq(
    boundaries: list[BoundaryCondition],
    path: str,
) -> bool:
    """Write a TELEMAC .liq file from boundary condition timeseries.

    Parameters
    ----------
    boundaries : list[BoundaryCondition]
        Boundary conditions with timeseries populated.
    path : str
        Output file path.

    Returns
    -------
    bool
        True if a .liq file was written, False if no timeseries data available.
    """
    # Filter to BCs with timeseries data
    ts_bcs = [bc for bc in boundaries if bc.timeseries is not None]
    if not ts_bcs:
        return False

    # Build a common time axis — union of all BC time arrays, then interpolate
    all_times = set()
    for bc in ts_bcs:
        for t in bc.timeseries["time"]:
            all_times.add(float(t))
    common_times = np.array(sorted(all_times))

    # Interpolate each BC onto common time axis
    columns: list[tuple[str, str, np.ndarray]] = []
    for i, bc in enumerate(ts_bcs):
        header, unit = _liq_column_name(bc, i)
        ts = bc.timeseries
        times = np.asarray(ts["time"], dtype=np.float64)
        values = np.asarray(ts["values"], dtype=np.float64)
        # Sort by time and deduplicate (keep last value for duplicate times)
        order = np.argsort(times, kind="stable")
        times = times[order]
        values = values[order]
        _, unique_idx = np.unique(times, return_index=True)
        # For duplicates, keep last occurrence: use reverse-unique trick
        _, last_idx = np.unique(times[::-1], return_index=True)
        last_idx = len(times) - 1 - last_idx
        times = times[last_idx]
        values = values[last_idx]
        interp_vals = np.interp(common_times, times, values)
        columns.append((header, unit, interp_vals))

    # Write file
    col_width = 14
    with open(path, "w") as f:
        f.write("# Liquid boundary time series\n")
        f.write("# Generated by TELEMAC Viewer import pipeline\n")

        # Header row
        f.write(f"{'T':>{col_width}}")
        for header, _, _ in columns:
            f.write(f"{header:>{col_width}}")
        f.write("\n")

        # Unit row
        f.write(f"{'s':>{col_width}}")
        for _, unit, _ in columns:
            f.write(f"{unit:>{col_width}}")
        f.write("\n")

        # Data rows
        for j, t in enumerate(common_times):
            f.write(f"{t:{col_width}.1f}")
            for _, _, values in columns:
                f.write(f"{values[j]:{col_width}.4f}")
            f.write("\n")

    return True
